# Generated by Django 2.1.7 on 2019-04-05 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('quantité', models.IntegerField()),
                ('categorie', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('depart', models.CharField(default='Paris', max_length=30)),
                ('arrive', models.CharField(default='Paris', max_length=30)),
                ('adresse', models.CharField(default='50 rue de la place', max_length=150)),
                ('adresse2', models.CharField(default='500 rue de la République', max_length=150)),
                ('datedepart', models.DateField()),
                ('livraison', models.BooleanField(default=True, verbose_name='livraison ?')),
                ('enlevement', models.BooleanField(default=False, verbose_name='enlevement ?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offreT', to='flexible.Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offreT', to='flexible.Produit')),
            ],
        ),
        migrations.RemoveField(
            model_name='offrecommandelivraison',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='offrecommandelivraison',
            name='adresse2',
        ),
        migrations.RemoveField(
            model_name='offrecommandelivraison',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='offrecommandelivraison',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='offrecommandelivraison',
            name='datedepart',
        ),
        migrations.RemoveField(
            model_name='offrecommandelivraison',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='offrecommandelivraison',
            name='refproduit',
        ),
        migrations.RemoveField(
            model_name='offrelivraison',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='offrelivraison',
            name='datearrive',
        ),
        migrations.RemoveField(
            model_name='offrelivraison',
            name='designation',
        ),
        migrations.AlterField(
            model_name='offrecommandelivraison',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisonTransport', to='flexible.OffreT'),
        ),
    ]
