# Generated by Django 2.1.7 on 2019-04-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexible', '0002_auto_20190405_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offret',
            old_name='datedepart',
            new_name='datearrive',
        ),
    ]
