# Generated by Django 2.1.7 on 2019-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
    ]
