# Generated by Django 2.1.7 on 2019-03-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0002_auto_20190322_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporteur',
            old_name='name',
            new_name='nom',
        ),
    ]
