# Generated by Django 2.1.7 on 2019-03-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0003_auto_20190322_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleContact_pour_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRoleContact', models.CharField(default='Null', max_length=42)),
                ('c_nom', models.CharField(default='Null', max_length=42)),
                ('c_nomCompte', models.CharField(default='Null', max_length=42)),
                ('c_horodatage', models.CharField(default='Null', max_length=42)),
                ('m_nom', models.CharField(default='Null', max_length=42)),
                ('m_nomCompte', models.CharField(default='Null', max_length=42)),
                ('m_horodatage', models.CharField(default='Null', max_length=42)),
                ('nom', models.CharField(default='Null', max_length=42)),
            ],
        ),
        migrations.RemoveField(
            model_name='typearticle_pour_client',
            name='fk_Client',
        ),
        migrations.RemoveField(
            model_name='typedestinataire_pour_client',
            name='fk_Client',
        ),
        migrations.RemoveField(
            model_name='typefournisseur_pour_client',
            name='fk_Client',
        ),
        migrations.RemoveField(
            model_name='typezonedepot_pour_client',
            name='fk_Client',
        ),
        migrations.AddField(
            model_name='boncommandesortie_pour_client',
            name='fk_Transporteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Transporteur'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_client',
            name='fk_Fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_client',
            name='fk_LettreVoitureEntree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.LettreVoitureEntree'),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='email',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='idContact',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='prenom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='telephone',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='dateCreation',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='fk_LettreVoitureEntree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.LettreVoitureEntree'),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='fk_Transporteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Transporteur'),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='idOrdreTransport',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ordretransport_pour_client',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='idTypeArticle',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typearticle_pour_client',
            name='nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='idTypeFournisseur',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typedestinataire_pour_client',
            name='nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='idTypeFournisseur',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typefournisseur_pour_client',
            name='nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='idTypeZoneDepot',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='typezonedepot_pour_client',
            name='nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='contact_pour_client',
            name='fk_RoleContact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.RoleContact_pour_Client'),
        ),
    ]
