# Generated by Django 2.1.7 on 2019-03-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0004_auto_20190328_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommandesortie_pour_client',
            name='fk_Destinataire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Destinataire'),
        ),
        migrations.AddField(
            model_name='boncommandesortie_pour_client',
            name='fk_TypeBonCommandeSortie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeBonCommandeSortie_pour_BonCommandeSortie'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_client',
            name='commentaire',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_client',
            name='dateReception',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_client',
            name='idBonLivraisonEntree',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_client',
            name='numeroBonLivraison',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_client',
            name='quantitePalette',
            field=models.CharField(default='Null', max_length=42),
        ),
    ]
