# Generated by Django 2.1.7 on 2019-03-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0005_auto_20190328_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommandeSortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBonCommandeSortie', models.CharField(default='Null', max_length=42)),
                ('termine', models.CharField(default='Null', max_length=42)),
                ('source', models.CharField(default='Null', max_length=42)),
                ('identifiantSource', models.CharField(default='Null', max_length=42)),
                ('numeroCommande', models.CharField(default='Null', max_length=42)),
                ('dateCommande', models.CharField(default='Null', max_length=42)),
                ('fk_Client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Client')),
                ('fk_Destinataire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Destinataire')),
                ('fk_Transporteur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Transporteur')),
                ('fk_TypeBonCommandeSortie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeBonCommandeSortie_pour_BonCommandeSortie')),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraisonEntree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBonLivraisonEntree', models.CharField(default='Null', max_length=42)),
                ('dateReception', models.CharField(default='Null', max_length=42)),
                ('numeroBonLivraison', models.CharField(default='Null', max_length=42)),
                ('quantitePalette', models.CharField(default='Null', max_length=42)),
                ('commentaire', models.CharField(default='Null', max_length=42)),
                ('fk_Client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Client')),
                ('fk_Fournisseur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur')),
                ('fk_LettreVoitureEntree', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.LettreVoitureEntree')),
            ],
        ),
    ]
