# Generated by Django 2.1.7 on 2019-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0006_boncommandesortie_bonlivraisonentree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitemanutentionentree',
            name='fk_Etiquette',
        ),
    ]
