# Generated by Django 2.1.7 on 2019-04-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0007_remove_unitemanutentionentree_fk_etiquette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommandeentree',
            name='fk_Fournisseur',
        ),
        migrations.RemoveField(
            model_name='colis_pour_boncommandeentree',
            name='fk_BonLivraisonEntree',
        ),
        migrations.RemoveField(
            model_name='unitemanutentionentree_pour_boncommandeentree',
            name='fk_BonLivraisonEntree',
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='codeClient',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='delaiPeremption',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='designationClient',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='designationFournisseur',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='dureeStockage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='fk_BonCommandeEntree',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonCommandeEntree'),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='fk_Fournisseur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur_pour_Article'),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='fk_TypeArticle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.typeArticle_pour_Article'),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='identifiantSource',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='poidsColisStandard',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='quantiteColisStandard',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='quantiteColisStockComplet',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='quantiteColisStockIncomplet',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='quantiteProduitStockComplet',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='quantiteProduitStockInComplet',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='quantiteUniteManutentionSortie',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='source',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='article_pour_boncommandeentree',
            name='stock',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='boncommandeentree_bonlivraisonentree_pour_boncommandeentree',
            name='idBonCommandeEntree_BonLivraisonEntree',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='boncommandeentree_bonlivraisonentree_pour_boncommandeentree',
            name='source',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fichier',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fk_BonCommandeEntree',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonCommandeEntree'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fk_Client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Client'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fk_Destinataire_litige',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Destinataire_pour_UniteManutentionEntree_litige'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fk_Fournisseur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fk_LettreVoitureEntree',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.LettreVoitureEntree'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='photo',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis_pour_boncommandeentree',
            name='idColis',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='dateLivraison',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='idLigneBonCommandeEntree',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='identifiantSource',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='quantiteColis',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='quantiteProduit',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='quantiteRecue',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='source',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='controle',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='fk_Article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Article'),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='idLigneBonLivraisonEntree',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteColis',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteColisAlivrer',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteColisLitige',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteColisRecu',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteCommande',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteCommandeRecue',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteDifference',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteDifferenceAutre',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteDifferenceRestante',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteProduit',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteProduitALivrer',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteProduitLitige',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteProduitRecu',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='quantiteRecue',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='termine',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='unitemanutentionentree_pour_boncommandeentree',
            name='id_dateReception',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='fk_Article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Article_pour_BonCommandeEntree'),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_boncommandeentree',
            name='fk_BonLivraisonEntree',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonLivraisonEntree'),
        ),
    ]
