# Generated by Django 2.1.7 on 2019-04-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0008_auto_20190411_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommandeentree',
            name='dateCommande',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='boncommandeentree',
            name='numeroCommande',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='boncommandeentree',
            name='source',
            field=models.CharField(default='Null', max_length=42),
        ),
    ]
