# Generated by Django 2.1.7 on 2019-04-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0009_auto_20190412_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fk_Fournisseur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur'),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='fk_Article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Article'),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='fk_Fournisseur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur'),
        ),
    ]
