# Generated by Django 2.1.7 on 2019-04-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0010_auto_20190415_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fk_Fournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur'),
        ),
    ]
