# Generated by Django 2.1.7 on 2019-04-24 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_stock', '0011_auto_20190415_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_partenaire', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_transporteur', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='article_historique_pour_article',
            old_name='designationFournisseur',
            new_name='dureestockage',
        ),
        migrations.RemoveField(
            model_name='article_historique_pour_article',
            name='dureeStockage',
        ),
    ]
