# Generated by Django 2.1.7 on 2019-04-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0012_auto_20190424_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_historique_pour_article',
            old_name='dureestockage',
            new_name='designationFournisseur',
        ),
        migrations.AddField(
            model_name='article_historique_pour_article',
            name='dureeStockage',
            field=models.CharField(default='Null', max_length=42),
        ),
    ]
