# Generated by Django 2.1.7 on 2019-04-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0013_auto_20190424_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_pour_Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArticle', models.CharField(default='Null', max_length=42)),
                ('codeFournisseur', models.CharField(default='Null', max_length=42)),
                ('codeClient', models.CharField(default='Null', max_length=42)),
                ('designationFournisseur', models.CharField(default='Null', max_length=42)),
                ('designationClient', models.CharField(default='Null', max_length=42)),
                ('dureeStockage', models.CharField(default='Null', max_length=42)),
                ('delaiPeremption', models.CharField(default='Null', max_length=42)),
                ('stock', models.CharField(default='Null', max_length=42)),
                ('poidsColisStandard', models.CharField(default='Null', max_length=42)),
                ('quantiteColisStandard', models.CharField(default='Null', max_length=42)),
                ('quantiteColisStockComplet', models.CharField(default='Null', max_length=42)),
                ('quantiteProduitStockComplet', models.CharField(default='Null', max_length=42)),
                ('quantiteColisStockIncomplet', models.CharField(default='Null', max_length=42)),
                ('quantiteProduitStockincomplet', models.CharField(default='Null', max_length=42)),
                ('quantiteUniteManutentionSortie', models.CharField(default='Null', max_length=42)),
                ('source', models.CharField(default='Null', max_length=42)),
                ('identifiantSource', models.CharField(default='Null', max_length=42)),
                ('fk_Fournisseur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur')),
                ('fk_TypeArticle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.typeArticle_pour_Article')),
            ],
        ),
        migrations.CreateModel(
            name='Colis_UniteManutentionSortie_pour_Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idColis_UniteManutentionSortie', models.CharField(default='Null', max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Litige_pour_Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLitige', models.CharField(default='Null', max_length=42)),
                ('nom', models.CharField(default='Null', max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='LotRetire_pour_Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRetrait', models.CharField(default='Null', max_length=42)),
                ('identifiantSource', models.CharField(default='Null', max_length=42)),
                ('idLotRetire', models.CharField(default='Null', max_length=42)),
                ('numeroLot', models.CharField(default='Null', max_length=42)),
                ('source', models.CharField(default='Null', max_length=42)),
                ('fk_Article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Article')),
            ],
        ),
        migrations.CreateModel(
            name='UniteManutentionEntree_pour_Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUniteManutentionEntree', models.CharField(default='Null', max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='UniteManutentionSortie_pour_Colis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUniteManutentionSortie', models.CharField(default='Null', max_length=42)),
            ],
        ),
        migrations.AddField(
            model_name='colis',
            name='c_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='c_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='c_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='datePeremption',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='emplacementConfirme',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='m_horodatage',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='m_nom',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='m_nomCompte',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='numeroLot',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='numerotation',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='quantiteProduit',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='colis',
            name='fk_litige',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Litige_pour_Colis'),
        ),
    ]
