# Generated by Django 2.1.7 on 2019-04-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0015_auto_20190425_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fk_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeZoneDepot'),
        ),
    ]
