# Generated by Django 2.1.7 on 2019-04-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0016_bonlivraisonentree_pour_boncommandeentree_fk_typezonedepot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraisonentree_pour_boncommandeentree',
            name='fk_TypeZoneDepot',
        ),
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='fk_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeZoneDepot'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_Client',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Client'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_Fournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur'),
        ),
    ]
