# Generated by Django 2.1.7 on 2019-04-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0017_auto_20190425_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='fk_LettreVoitureEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.LettreVoitureEntree'),
        ),
    ]
