# Generated by Django 2.1.7 on 2019-04-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0018_bonlivraisonentree_fk_lettrevoitureentree'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='fk_BonCommandeEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonCommandeEntree'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='fk_UniteManutentionEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.UniteManutentionEntree'),
        ),
    ]
