# Generated by Django 2.1.7 on 2019-04-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0019_auto_20190429_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneBonLivraisonEntree_pour_BonLivraisonEntree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLigneBonLivraisonEntree', models.CharField(default='Null', max_length=42)),
                ('controle', models.CharField(default='Null', max_length=42)),
                ('quantiteColis', models.CharField(default='Null', max_length=42)),
                ('quantiteColisAlivrer', models.CharField(default='Null', max_length=42)),
                ('quantiteColisLitige', models.CharField(default='Null', max_length=42)),
                ('quantiteColisRecu', models.CharField(default='Null', max_length=42)),
                ('quantiteCommande', models.CharField(default='Null', max_length=42)),
                ('quantiteCommandeRecue', models.CharField(default='Null', max_length=42)),
                ('quantiteDifference', models.CharField(default='Null', max_length=42)),
                ('quantiteDifferenceAutre', models.CharField(default='Null', max_length=42)),
                ('quantiteDifferenceRestante', models.CharField(default='Null', max_length=42)),
                ('quantiteProduit', models.CharField(default='Null', max_length=42)),
                ('quantiteProduitAlivrer', models.CharField(default='Null', max_length=42)),
                ('quantiteProduitLitige', models.CharField(default='Null', max_length=42)),
                ('quantiteProduitRecu', models.CharField(default='Null', max_length=42)),
                ('termine', models.CharField(default='Null', max_length=42)),
                ('fk_Article', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Article')),
                ('fk_BonLivraisonEntree', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonLivraisonEntree')),
            ],
        ),
    ]
