# Generated by Django 2.1.7 on 2019-05-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0020_lignebonlivraisonentree_pour_bonlivraisonentree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='fk_Transporteur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Transporteur'),
        ),
    ]
