# Generated by Django 2.1.7 on 2019-05-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0021_auto_20190503_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='fk_Destinataire',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Destinataire'),
        ),
    ]
