# Generated by Django 2.1.7 on 2019-05-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0022_bonlivraisonentree_fk_destinataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fk_TypeZone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeZoneDepot'),
        ),
    ]
