# Generated by Django 2.1.7 on 2019-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0023_auto_20190503_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeZoneDepot_pour_Client',
        ),
    ]
