# Generated by Django 2.1.7 on 2019-05-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0024_delete_typezonedepot_pour_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraisonentree',
            name='fk_BonCommandeEntree',
        ),
        migrations.RemoveField(
            model_name='bonlivraisonentree',
            name='fk_UniteManutentionEntree',
        ),
    ]
