# Generated by Django 2.1.7 on 2019-05-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0025_auto_20190506_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraisonentree_pour_lettrevoiturelettrevoitureentree',
            name='fk_Client',
        ),
        migrations.AddField(
            model_name='bonlivraisonentree_pour_lettrevoiturelettrevoitureentree',
            name='fk_BonLivraisonEntree',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonLivraisonEntree'),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='datereception',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='numerorecepisse',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='quantitecolis',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='quantitepalette',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='reclanumerorecepisse',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='reclaquantitecolis',
            field=models.CharField(default='Null', max_length=42),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='reclaquantitepalette',
            field=models.CharField(default='Null', max_length=42),
        ),
    ]
