# Generated by Django 2.1.7 on 2019-05-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0027_auto_20190506_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lettrevoitureentree',
            old_name='reclanumerorecepisse',
            new_name='reclacomm',
        ),
    ]
