# Generated by Django 2.1.7 on 2019-05-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0028_auto_20190506_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='fk_BonLivraisonEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonLivraisonEntree'),
        ),
    ]
