# Generated by Django 2.1.7 on 2019-05-13 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0030_auto_20190513_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fk_TypeArticle',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.typeArticle_pour_Article'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fk_TypeDestinataire',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeDestinataire_pour_Destinataire'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fk_TypeFournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeFournisseur_pour_Fournisseur'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fk_TypeZone',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeZoneDepot'),
        ),
    ]
