# Generated by Django 2.1.7 on 2019-05-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0031_auto_20190513_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommandesortie_pour_client',
            name='fk_Client',
        ),
        migrations.RemoveField(
            model_name='boncommandesortie_pour_client',
            name='fk_Destinataire',
        ),
        migrations.RemoveField(
            model_name='boncommandesortie_pour_client',
            name='fk_Transporteur',
        ),
        migrations.RemoveField(
            model_name='boncommandesortie_pour_client',
            name='fk_TypeBonCommandeSortie',
        ),
        migrations.RemoveField(
            model_name='bonlivraisonentree_pour_client',
            name='fk_Client',
        ),
        migrations.RemoveField(
            model_name='bonlivraisonentree_pour_client',
            name='fk_Fournisseur',
        ),
        migrations.RemoveField(
            model_name='bonlivraisonentree_pour_client',
            name='fk_LettreVoitureEntree',
        ),
        migrations.RemoveField(
            model_name='ordretransport_pour_client',
            name='fk_Client',
        ),
        migrations.RemoveField(
            model_name='ordretransport_pour_client',
            name='fk_LettreVoitureEntree',
        ),
        migrations.RemoveField(
            model_name='ordretransport_pour_client',
            name='fk_Transporteur',
        ),
        migrations.DeleteModel(
            name='TypeArticle_pour_Client',
        ),
        migrations.DeleteModel(
            name='TypeDestinataire_pour_Client',
        ),
        migrations.DeleteModel(
            name='TypeFournisseur_pour_Client',
        ),
        migrations.DeleteModel(
            name='BonCommandeSortie_pour_Client',
        ),
        migrations.DeleteModel(
            name='BonLivraisonEntree_pour_Client',
        ),
        migrations.DeleteModel(
            name='OrdreTransport_pour_Client',
        ),
    ]
