# Generated by Django 2.1.7 on 2019-05-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0032_auto_20190513_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='fk_ZoneDepot_pour_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.ZoneDepot_pour_TypeZoneDepot'),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='fk_BonLivraisonEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonLivraisonEntree'),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='fk_ZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.ZoneDepot_pour_TypeZoneDepot'),
        ),
    ]
