# Generated by Django 2.1.7 on 2019-05-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0034_auto_20190515_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_historique_pour_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_nom', models.CharField(default='Null', max_length=42)),
                ('c_nomCompte', models.CharField(default='Null', max_length=42)),
                ('c_horodatage', models.CharField(default='Null', max_length=42)),
                ('m_nom', models.CharField(default='Null', max_length=42)),
                ('m_nomCompte', models.CharField(default='Null', max_length=42)),
                ('m_horodatage', models.CharField(default='Null', max_length=42)),
                ('idArticle_historique', models.CharField(default='Null', max_length=42)),
                ('nomFournisseur', models.CharField(default='Null', max_length=42)),
                ('codeFournisseur', models.CharField(default='Null', max_length=42)),
                ('designationFournisseur', models.CharField(default='Null', max_length=42)),
                ('codeClient', models.CharField(default='Null', max_length=42)),
                ('designationClient', models.CharField(default='Null', max_length=42)),
                ('poids', models.CharField(default='Null', max_length=42)),
                ('delaiPeremption', models.CharField(default='Null', max_length=42)),
                ('dureeStockage', models.CharField(default='Null', max_length=42)),
                ('fk_Article', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Article')),
                ('fk_Fournisseur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Fournisseur')),
            ],
        ),
        migrations.RenameField(
            model_name='unitemanutentionentree',
            old_name='idUnitManutentionEntree',
            new_name='idUniteManutentionEntree',
        ),
    ]
