# Generated by Django 2.1.7 on 2019-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0035_auto_20190515_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgaccueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgaccueil')),
            ],
        ),
        migrations.CreateModel(
            name='imgarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgarticle')),
            ],
        ),
        migrations.CreateModel(
            name='imgbcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgbcs')),
            ],
        ),
        migrations.CreateModel(
            name='imgble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgble')),
            ],
        ),
        migrations.CreateModel(
            name='imgbls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgbls')),
            ],
        ),
        migrations.CreateModel(
            name='imgclient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgclient')),
            ],
        ),
        migrations.CreateModel(
            name='imgcolis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgcolis')),
            ],
        ),
        migrations.CreateModel(
            name='imgdestinataires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgdestinataires')),
            ],
        ),
        migrations.CreateModel(
            name='imgfournisseurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgfournisseurs')),
            ],
        ),
        migrations.CreateModel(
            name='imglve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imglve')),
            ],
        ),
        migrations.CreateModel(
            name='imgtransporteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgtransporteurs')),
            ],
        ),
        migrations.CreateModel(
            name='imgumentree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='imgumentree')),
            ],
        ),
    ]
