# Generated by Django 2.1.7 on 2019-05-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0036_imgaccueil_imgarticle_imgbcs_imgble_imgbls_imgclient_imgcolis_imgdestinataires_imgfournisseurs_imglv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imgaccueil',
        ),
    ]
