# Generated by Django 2.1.7 on 2019-05-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0037_delete_imgaccueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgaccueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
