# Generated by Django 2.1.7 on 2019-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0038_imgaccueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgaccueil',
            name='cover',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='imgaccueil',
            name='title',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
