# Generated by Django 2.1.7 on 2019-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0040_auto_20190517_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgaccueil',
            name='cover',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imgaccueil',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
