# Generated by Django 2.1.7 on 2019-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0041_auto_20190520_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover1', models.ImageField(upload_to='images/')),
                ('cover2', models.ImageField(upload_to='images/')),
                ('cover3', models.ImageField(upload_to='images/')),
                ('cover4', models.ImageField(upload_to='images/')),
                ('cover5', models.ImageField(upload_to='images/')),
                ('cover6', models.ImageField(upload_to='images/')),
                ('cover7', models.ImageField(upload_to='images/')),
                ('cover8', models.ImageField(upload_to='images/')),
                ('cover9', models.ImageField(upload_to='images/')),
                ('cover10', models.ImageField(upload_to='images/')),
                ('cover11', models.ImageField(upload_to='images/')),
                ('cover12', models.ImageField(upload_to='images/')),
                ('cover13', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='imgaccueil',
        ),
        migrations.DeleteModel(
            name='imgarticle',
        ),
        migrations.DeleteModel(
            name='imgbcs',
        ),
        migrations.DeleteModel(
            name='imgble',
        ),
        migrations.DeleteModel(
            name='imgbls',
        ),
        migrations.DeleteModel(
            name='imgclient',
        ),
        migrations.DeleteModel(
            name='imgcolis',
        ),
        migrations.DeleteModel(
            name='imgdestinataires',
        ),
        migrations.DeleteModel(
            name='imgfournisseurs',
        ),
        migrations.DeleteModel(
            name='imglve',
        ),
        migrations.DeleteModel(
            name='imgtransporteurs',
        ),
        migrations.DeleteModel(
            name='imgumentree',
        ),
    ]
