# Generated by Django 2.1.7 on 2019-05-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0042_auto_20190520_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteManutentionSortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUniteManutentionSortie', models.CharField(default='Null', max_length=42)),
                ('c_nom', models.CharField(default='Null', max_length=42)),
                ('c_nomCompte', models.CharField(default='Null', max_length=42)),
                ('c_horodatage', models.CharField(default='Null', max_length=42)),
                ('m_nom', models.CharField(default='Null', max_length=42)),
                ('m_nomCompte', models.CharField(default='Null', max_length=42)),
                ('m_horodatage', models.CharField(default='Null', max_length=42)),
                ('numero', models.CharField(default='Null', max_length=42)),
                ('dateReception', models.CharField(default='Null', max_length=42)),
                ('stock', models.CharField(default='Null', max_length=42)),
                ('fk_UniteManutentionEntre', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.UniteManutentionEntree')),
            ],
        ),
        migrations.AddField(
            model_name='colis',
            name='fk_Article',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Article'),
        ),
        migrations.AddField(
            model_name='colis',
            name='fk_UniteManutentionEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.UniteManutentionEntree'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover10',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover11',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover12',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover13',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover6',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover7',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover8',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuimages',
            name='cover9',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='colis',
            name='fk_UniteManutentionSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.UniteManutentionSortie'),
        ),
    ]
