# Generated by Django 2.1.7 on 2019-05-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0043_auto_20190523_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitigeDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLitige', models.CharField(default='Null', max_length=42)),
                ('nom', models.CharField(default='Null', max_length=42)),
            ],
        ),
        migrations.RenameModel(
            old_name='Litige_pour_Colis',
            new_name='Litige',
        ),
    ]
