# Generated by Django 2.1.7 on 2019-05-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0044_auto_20190523_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='fk_litige',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Litige'),
        ),
    ]
