# Generated by Django 2.1.7 on 2019-05-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0045_auto_20190523_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='fk_LitigeDecision',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.LitigeDecision'),
        ),
        migrations.AddField(
            model_name='colis',
            name='fk_ZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.ZoneDepot_pour_TypeZoneDepot'),
        ),
    ]
