# Generated by Django 2.1.7 on 2019-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0048_auto_20190611_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitemanutentionsortie',
            name='dateExpedition',
            field=models.CharField(default=0, max_length=42),
        ),
        migrations.AddField(
            model_name='unitemanutentionsortie',
            name='dateOuverture',
            field=models.CharField(default=0, max_length=42),
        ),
    ]
