# Generated by Django 2.1.7 on 2019-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0049_auto_20190611_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuimages',
            name='cover14',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
