# Generated by Django 2.1.7 on 2019-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0050_menuimages_cover14'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='codeClient',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='codeFournisseur',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='delaiPeremption',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='designationClient',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='designationFournisseur',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='dureeStockage',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='idArticle',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='identifiantSource',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='poidsColisStandard',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantiteColisStandard',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantiteColisStockComplet',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantiteColisStockIncomplet',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantiteProduitStockComplet',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantiteProduitStockIncomplet',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantiteUniteManutentionSortie',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='codeClient',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='codeFournisseur',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='delaiPeremption',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='designationClient',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='designationFournisseur',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='dureeStockage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='idArticle_historique',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='nomFournisseur',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='poids',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='dateCommande',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='idBonCommandeEntree',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='numeroCommande',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandeentree',
            name='source',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='dateCommande',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='idBonCommandeSortie',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='identifiantSource',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='numeroCommande',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='source',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='termine',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='commentaire',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='dateReception',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='idBonLivraisonEntree',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='numeroBonLivraison',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='quantitePalette',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='codeTracking',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='dateImpression',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='idBonLivraisonSortie',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='numeroBonLivraison',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='prixExpedition',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='commentaire',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='idClient',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='identifiantSource',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='tva',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='colle',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='datePeremption',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='emplacementConfirme',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='idColis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='numeroLot',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='numerotation',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='colis',
            name='quantiteProduit',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='email',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='idContact',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='prenom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='telephone',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseFacturation',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison_codePostal',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison_complement_1',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison_complement_2',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison_localite',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison_numero',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='adresseLivraison_rue',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='codeUM',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='commentaire',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='delaiPeremption',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='departement',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='email',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='idDestinataire',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='identifiantBonLivraison',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='identifiantSource',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='ordreTri',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='source',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='telephone',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='idFournisseur',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='identifiantSource',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='source',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='datereception',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='idLettreVoitureEntree',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='numerorecepisse',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='quantitecolis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='quantitepalette',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='reclacomm',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='reclaquantitecolis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoitureentree',
            name='reclaquantitepalette',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='datereception',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='idLettreVoitureSortie',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='numerorecepisse',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='quantitecolis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='quantitepalette',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='reclacomm',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='reclaquantitecolis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lettrevoituresortie',
            name='reclaquantitepalette',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='dateLivraison',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='idLigneBonCommandeEntree',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='identifiantSource',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='quantiteColis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='quantiteProduit',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='quantiteRecue',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='source',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='differenceCommandeLivre',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='differenceCommandePotentiel',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='idLigneBonCommandeSortie',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='identifiantSource',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='priorite',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='quantiteColisCommande',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='quantiteColisLivre',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='quantiteColisPotentielle',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='quantiteProduitALivrer',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='quantiteProduitCommande',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='quantiteProduitLivre',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='quantiteProduitPotentielle',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='source',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_import_boncommandesortie',
            name='termine',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='controle',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='idLigneBonLivraisonEntree',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteColis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteColisAlivrer',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteColisLitige',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteColisRecu',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteCommande',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteCommandeRecue',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteDifference',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteDifferenceAutre',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteDifferenceRestante',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteProduit',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteProduitAlivrer',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteProduitLitige',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='quantiteProduitRecu',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='termine',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='idLigneBonLivraisonSortie',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='quantiteColis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='stat_quantiteColis',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='litige',
            name='idLitige',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='litige',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='litigedecision',
            name='idLitige',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='litigedecision',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='codeISO_2',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='codeISO_3',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='idPays',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='pays_pour_destinataire',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='idRoleContact',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='rolecontact_pour_client',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='idTransporteur',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='idTypeArticle',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typearticle_pour_article',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='idTypeBonCommandeSortie',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typeboncommandesortie_pour_boncommandesortie',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='idTypeDestinataire',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typedestinataire_pour_destinataire',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='idTypeFournisseur',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typefournisseur_pour_fournisseur',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='idTypeZoneDepot',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='typezonedepot',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='dateReception',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='idUniteManutentionEntree',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='numero',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='stock',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='dateExpedition',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='dateOuverture',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='dateReception',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='idUniteManutentionSortie',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='numero',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='poidsBrut',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='poidsDifference',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='poidsNet',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='poidsTare',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='c_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='c_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='c_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='idZoneDepot',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='m_horodatage',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='m_nom',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='m_nomCompte',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='nom',
            field=models.CharField(default=0, max_length=80),
        ),
    ]
