# Generated by Django 2.1.7 on 2019-06-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0053_remove_boncommandesortie_fk_typeboncommandesortie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LigneBonCommandeSortie_pour_import_BonCommandeSortie',
            new_name='LigneBonCommandeSortie_pour_BonCommandeSortie',
        ),
    ]
