# Generated by Django 2.1.7 on 2019-06-17 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0054_auto_20190613_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_pour_client',
            name='fk_RoleContact',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.RoleContact_pour_Client'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='fk_TypeFournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeFournisseur_pour_Fournisseur'),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='fk_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.TypeZoneDepot'),
        ),
    ]
