# Generated by Django 2.1.7 on 2019-06-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0056_auto_20190618_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='fk_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.Client'),
        ),
    ]
