# Generated by Django 2.1.7 on 2019-06-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0057_auto_20190618_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import_ligneboncommandesortie_pour_import_boncommandesortie',
            name='fk_BonCommandeSortie',
        ),
        migrations.DeleteModel(
            name='import_BonCommandeSortie',
        ),
        migrations.DeleteModel(
            name='import_LigneBonCommandeSortie_pour_import_BonCommandeSortie',
        ),
    ]
