# Generated by Django 2.1.7 on 2019-07-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0059_auto_20190628_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fk_Fournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Fournisseur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fk_TypeArticle',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.typeArticle_pour_Article'),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='fk_Article',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Article'),
        ),
        migrations.AlterField(
            model_name='article_historique_pour_article',
            name='fk_Fournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Fournisseur'),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='fk_Client',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Client'),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='fk_Destinataire',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Destinataire'),
        ),
        migrations.AlterField(
            model_name='boncommandesortie',
            name='fk_Transporteur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Transporteur'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_Client',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Client'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_Destinataire',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Destinataire'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_Fournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Fournisseur'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_LettreVoitureEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.LettreVoitureEntree'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.TypeZoneDepot'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonentree',
            name='fk_ZoneDepot_pour_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.ZoneDepot_pour_TypeZoneDepot'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='fk_BonCommandeSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonCommandeSortie'),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='fk_LettreVoitureSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.LettreVoitureSortie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fk_TypeArticle',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.typeArticle_pour_Article'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fk_TypeDestinataire',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.TypeDestinataire_pour_Destinataire'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fk_TypeFournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.TypeFournisseur_pour_Fournisseur'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fk_TypeZone',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.TypeZoneDepot'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fk_Article',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Article'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fk_LitigeDecision',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.LitigeDecision'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fk_UniteManutentionEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.UniteManutentionEntree'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fk_UniteManutentionSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.UniteManutentionSortie'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fk_ZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.ZoneDepot_pour_TypeZoneDepot'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fk_litige',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Litige'),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='fk_Client',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Client'),
        ),
        migrations.AlterField(
            model_name='contact_pour_client',
            name='fk_RoleContact',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.RoleContact_pour_Client'),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='fk_Pays',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Pays_pour_Destinataire'),
        ),
        migrations.AlterField(
            model_name='destinataire',
            name='fk_TypeDestinataire',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.TypeDestinataire_pour_Destinataire'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='fk_TypeFournisseur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.TypeFournisseur_pour_Fournisseur'),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='fk_Article',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Article'),
        ),
        migrations.AlterField(
            model_name='ligneboncommandeentree_pour_boncommandeentree',
            name='fk_BonCommandeEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonCommandeEntree'),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_boncommandesortie',
            name='fk_Article',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Article'),
        ),
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_boncommandesortie',
            name='fk_BonCommandeSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonCommandeSortie'),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='fk_Article',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Article'),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonentree_pour_bonlivraisonentree',
            name='fk_BonLivraisonEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonLivraisonEntree'),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='fk_Article',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Article'),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='fk_BonLivraisonSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonLivraisonSortie'),
        ),
        migrations.AlterField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='fk_Transporteur',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Transporteur'),
        ),
        migrations.AlterField(
            model_name='unitemanutentionentree',
            name='fk_BonLivraisonEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonLivraisonEntree'),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='fk_BonCommandeSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonCommandeSortie'),
        ),
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='fk_BonLivraisonSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.BonLivraisonSortie'),
        ),
        migrations.AlterField(
            model_name='zonedepot_pour_typezonedepot',
            name='fk_TypeZoneDepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.TypeZoneDepot'),
        ),
    ]
