# Generated by Django 2.1.7 on 2019-07-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0060_auto_20190705_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='fk_UniteManutentionEntree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.UniteManutentionEntree'),
        ),
    ]
