# Generated by Django 2.1.7 on 2019-07-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0061_auto_20190710_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitemanutentionentree',
            name='fk_ZoneDepot',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.ZoneDepot_pour_TypeZoneDepot'),
        ),
    ]
