# Generated by Django 2.1.7 on 2019-07-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0062_unitemanutentionentree_fk_zonedepot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitemanutentionsortie',
            name='fk_BonCommandeSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonCommandeSortie'),
        ),
    ]
