# Generated by Django 2.1.7 on 2019-07-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0063_auto_20190710_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='fichier',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media_ble/'),
        ),
        migrations.AddField(
            model_name='bonlivraisonentree',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media_ble/'),
        ),
    ]
