# Generated by Django 2.1.7 on 2019-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0064_auto_20190710_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='fichier',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media_lve/'),
        ),
        migrations.AddField(
            model_name='lettrevoitureentree',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media_lve/'),
        ),
    ]
