# Generated by Django 2.1.7 on 2019-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0065_auto_20190715_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommandesortie',
            name='fichier',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media_bcs/'),
        ),
    ]
