# Generated by Django 2.1.7 on 2019-07-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0066_boncommandesortie_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneboncommandesortie_pour_boncommandesortie',
            name='quantiteProduitCommandestats',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
