# Generated by Django 2.1.7 on 2019-07-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0067_ligneboncommandesortie_pour_boncommandesortie_quantiteproduitcommandestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='fk_UniteManutentionSortie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.UniteManutentionSortie'),
        ),
    ]
