# Generated by Django 2.1.7 on 2019-07-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0068_auto_20190718_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='fk_UniteManutentionSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='gestion_stock.UniteManutentionSortie'),
        ),
    ]
