# Generated by Django 2.1.7 on 2019-07-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0070_auto_20190718_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitemanutentionsortie',
            old_name='dateReception',
            new_name='dateFermeture',
        ),
        migrations.AlterField(
            model_name='colis',
            name='fk_UniteManutentionSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.UniteManutentionSortie'),
        ),
    ]
