# Generated by Django 2.1.7 on 2019-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0071_auto_20190722_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonsortie',
            name='qtecolis',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
