# Generated by Django 2.1.7 on 2019-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0072_bonlivraisonsortie_qtecolis'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraisonsortie',
            name='fichier',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media_bls/'),
        ),
    ]
