# Generated by Django 2.1.7 on 2019-07-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0073_bonlivraisonsortie_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneboncommandesortie_pour_boncommandesortie',
            name='fk_BonCommandeSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonCommandeSortie'),
        ),
    ]
