# Generated by Django 2.1.7 on 2019-07-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0074_auto_20190725_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='fk_Transporteur',
        ),
        migrations.AddField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='quantiteProduit',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
