# Generated by Django 2.1.7 on 2019-07-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0075_auto_20190725_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignebonlivraisonsortie_pour_bonlivraisonsortie',
            name='fk_BonLivraisonSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonLivraisonSortie'),
        ),
    ]
