# Generated by Django 2.1.7 on 2019-08-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0076_auto_20190725_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='imprime',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='bonlivraisonsortie',
            name='fk_BonCommandeSortie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.BonCommandeSortie'),
        ),
    ]
