# Generated by Django 2.1.7 on 2019-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0077_auto_20190801_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='imprime',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
