# Generated by Django 2.1.7 on 2019-08-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0078_auto_20190801_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Destinataire_pour_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArticle_Destinataire', models.CharField(default=0, max_length=150)),
                ('delaiPeremption', models.CharField(default=0, max_length=150)),
                ('fk_Article', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Article')),
                ('fk_Destinataire', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.Destinataire')),
            ],
        ),
    ]
